Film1/Film/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Film1/movie/urls.py
from django.contrib import admin
from django.urls import path,include

from movie import views
app_name='movie'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('viewfilm/',views.viewfilm,name="viewfilm"),
    path('viewfilmbyid/<int:p>',views.viewfilmbyid,name="viewfilmbyid"),
path('deletefilmbyid/<int:p>',views.deletefilmbyid,name="deletefilmbyid"),
path('editfilmbyid/<int:p>',views.editfilmbyid,name="editfilmbyid"),
    # path('addfilm1/',views.addfilm1,name="addfilm1"),



]

Film1/movie/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    cover=models.ImageField(upload_to="movie/cover",null=True,blank=True)
    name=models.CharField(max_length=20)
    des=models.CharField(max_length=20)
    year=models.IntegerField()

Film1/Film/forms.py
from django import forms
from movie.models import Movie



class bookform(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'

Film1/movie/views.py
from django.shortcuts import render
from movie.models import Movie
from Film.forms import bookform
# Create your views here.

def home(request):
    return render(request,'home.html')


def viewfilm(request):
    b = Movie.objects.all()
    return render(request, 'viewfilm.html', {'film': b})


#
# def addfilm1(request):#builed in
#     form=bookform()
#     if(request.method=="POST"):
#         form=bookform(request.POST)
#         if(form.is_valid()):
#             form.save()
#             return viewfilm(request)

def viewfilmbyid(request,p):
    b=Movie.objects.get(id=p)
    return render(request, 'viewfilmbyid.html', {'film': b})


def deletefilmbyid(request,p):
    b = Movie.objects.get(id=p)
    b.delete()
    return viewfilm(request)


def editfilmbyid(request,p):
    b = Movie.objects.get(id=p)
    form = bookform(instance=b)
    if (request.method == "POST"):
        form = bookform(request.POST, request.FILES, instance=b)
        if (form.is_valid()):
            form.save()
            return viewfilm(request)
    return render(request, 'edit.html', {'form': form})

Film1/templates/addfilm.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h1></h1>
    <br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{form.as_table}}
        </table>
    <input type="submit">
</form></center>

{% endblock %}

Film1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <style>
    .nav-link
    {
    color:red;
    font-weight:bold;
    }
  </style>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <style>
    .nav-link
    {
    color:red;
    font-weight:20px;
    }
  </style>
</head>
<body style="background-color:#caedd3">

<nav class="navbar navbar-expand-lg bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">FILM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'movie:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'movie:viewfilm' %}">FILMS</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

Film1/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{form.as_table}}
        </table>
    <input type="submit">
</form>



{% endblock %}

Film1/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h1>Film app</h1>
    <br>

<img src="{% static 'images/film.jpg' %}" style="height:100%;width:100%"></center>

{% endblock %}

Film1/templates/viewfilm.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br>
<div class="container">
    <div class="row">
{% for i in film %}




    <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
  <img src="{{i.cover.url}}" class="card-img-top" alt="..." height="150px" width="100%">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.des}}</p>
      <p class="card-text">{{i.year}}</p>
    <a href="{% url 'movie:viewfilmbyid' i.id %}" class="btn btn-primary">See details</a>
      <a href="{% url 'movie:deletefilmbyid' i.id %}" class="btn btn-primary">Delete</a><br><br>
      <a href="{% url 'movie:editfilmbyid' i.id %}" class="btn btn-primary">Edit</a>
  </div>
</div>
    </div>


<br><br>
{% endfor %}
    </div></div>
{% endblock %}

Film1/templates/viewfilmbyid.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h1>See Details</h1>
</center>


<center>
    <h1>VIEW BOOK</h1>
    <br></center>
<table style="border-color:black" class="table table-bordered">
  <tr>
    <th>Film</th>
    <td><img src="{{film.cover.url}}" style="height:300px;width:400px"></td>
  </tr>
  <tr>
    <th>TITLE</th>
    <td>{{film.name}}</td>
  </tr>
   <tr>
    <th>Description</th>
    <td>{{film.des}}</td>
  </tr>
    <tr>
    <th>Year</th>
    <td>{{film.year}}</td>
  </tr>

</table>





{% endblock %}